development:
  bin_path: /usr/local/coreseek/bin
  max_children: 1
  mem_limit: 128M
  #workers: prefork
  charset_type: zh_cn.utf-8
  charset_dictpath: /usr/local/mmseg4/etc/
#charset_dictpath: /home/muzik/Aptana/yl/config/etc/ 
  port: 9322
  ngram_len: 0
  indexed_models:
    - Yaopin
    - Jibing
production:
  bin_path: /usr/local/coreseek/bin
  max_children: 4
  mem_limit: 256M
  # workers: prefork
  charset_type: zh_cn.utf-8
  charset_dictpath: /dat/www/jxjw/current/config/etc/
  #charset_dictpath: /usr/local/mmseg3/etc/
  port: 9322
